have_fun: false
memory_config:
  disabled: false
code_review:
  disable: true
  comment_severity_threshold: LOW
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: false
    code_review: false
    include_drafts: false
ignore_patterns:
- '**/*.png'
- '**/*.jpg'
- '**/*.ogg'
- '**/*.mp3'
- '**/*.wav'
- 'RobustToolbox/**'
- '**/Migrations/**'
- 'Resources/Maps/**/*.yml'
