name: Publish

concurrency:
  group: publish
  cancel-in-progress: true

on:
  workflow_dispatch:
  #schedule:
    # - cron: '0 1 * * *'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
  # SS220 Discord Notifier bgn
    - name: SS220 PN2D - Start # PN2D - Publish notify to Discord
      env:
        DISCORD_PUBLISH_NOTIFY: ${{ secrets.DISCORD_PUBLISH_NOTIFY }}
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{"username": "GitHub Publish Changes",
        "avatar_url": "https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/refs/heads/master/logo.png",
        "embeds": [{
            "title": "<a:nian:1179921939301670992> –ó–∞–ø—É—â–µ–Ω–æ –æ–±–Ω–æ–≤–ª–µ–Ω–∏–µ –ø–æ `${{GITHUB.REF_NAME}}` –≤–µ—Ç–∫–µ!",
            "description": "–ü—Ä–∏ —É—Å–ø–µ—à–Ω–æ–º –æ–±–Ω–æ–≤–ª–µ–Ω–∏–∏, —Å–µ—Ä–≤–µ—Ä–∞ –Ω–∞ —ç—Ç–æ–π –≤–µ—Ç–∫–µ –±—É–¥—É—Ç –æ–±–Ω–æ–≤–ª–µ–Ω—ã",
            "color": 12341258
          }]
        }' \
        $DISCORD_PUBLISH_NOTIFY
  # SS220 Discord Notifier end
    - name: Fail if we are attempting to run on the master branch
      if: ${{GITHUB.REF_NAME == 'master' && github.repository == 'SerbiaStrong-220/space-station-14'}}
      run: exit 1

  # SS220 custom install start
   # - name: Install dependencies
   #   run: sudo apt-get install -y python3-paramiko python3-lxml
  # SS220 custom install end

    - uses: actions/checkout@v4.2.2
      with:
        submodules: 'recursive'

    # Corvax-Secrets-Start
    #- name: Setup secrets
    #  env:
    #    SSH_KEY: ${{ secrets.SECRETS_PRIVATE_KEY }}
    #  if: ${{ env.SSH_KEY != '' }}
    #  run: |
    #    mkdir ~/.ssh
    #    echo "${{ secrets.SECRETS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    #    chmod 600 ~/.ssh/id_rsa
    #    echo "HOST *" > ~/.ssh/config
    #    echo "StrictHostKeyChecking no" >> ~/.ssh/config
    #    git -c submodule.Secrets.update=checkout submodule update --init
    #    cp -R Secrets/Prototypes Resources/Prototypes/CorvaxSecrets
    #    cp -R Secrets/ServerPrototypes Resources/Prototypes/CorvaxSecretsServer
    # Corvax-Secrets-End

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: 9.0.x

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Install dependencies
      run: dotnet restore

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --platform win-x64 --platform win-arm64 --platform linux-x64 --platform linux-arm64 --platform osx-x64 --platform osx-arm64

    - name: Package client
      run: dotnet run --project Content.Packaging client --no-wipe-release

    - name: Publish version
      run: Tools/publish_multi_request.py
      env:
        PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        GITHUB_REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}
  # SS220 Discord Notifier bgn
  # –û–±–Ω–æ–≤–ª–µ–Ω–∏–µ –ø–æ–ª—É—á–µ–Ω–æ, —Å–µ—Ä–≤–µ—Ä –∞–≤—Ç–æ–º–∞—Ç–∏—á–µ—Å–∫–∏ –ø–µ—Ä–µ–∑–∞–ø—É—Å—Ç–∏—Ç—Å—è –¥–ª—è –æ–±–Ω–æ–≤–ª–µ–Ω–∏—è –≤ –∫–æ–Ω—Ü–µ —ç—Ç–æ–≥–æ —Ä–∞—É–Ω–¥–∞.
    - name: SS220 PN2D - End
      if: success()
      env:
        DISCORD_PUBLISH_NOTIFY: ${{ secrets.DISCORD_PUBLISH_NOTIFY }}
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{"username": "GitHub Publish Changes",
        "avatar_url": "https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/refs/heads/master/logo.png",
        "embeds": [{
            "title": "‚úÖ –£—Å–ø–µ—à–Ω–æ –æ–±–Ω–æ–≤–ª–µ–Ω–∏–µ –ø–æ `${{GITHUB.REF_NAME}}` –≤–µ—Ç–∫–µ!",
            "description": "–û–±–Ω–æ–≤–ª–µ–Ω–∏–µ –ø—Ä–æ—à–ª–æ —É—Å–ø–µ—à–Ω–æ.",
            "color": 7584042
          }]
        }' \
        $DISCORD_PUBLISH_NOTIFY
    - name: SS220 PN2D - Failure
      if: failure()
      env:
        DISCORD_PUBLISH_NOTIFY: ${{ secrets.DISCORD_PUBLISH_NOTIFY }}
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{
          "username": "GitHub Publish Changes",
          "avatar_url": "https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/refs/heads/master/logo.png",
          "embeds": [{
            "title": "‚ùå –ù—É—Å–ø–µ—à–Ω–æ –æ–±–Ω–æ–≤–ª–µ–Ω–∏–µ –ø–æ `${{GITHUB.REF_NAME}}` –≤–µ—Ç–∫–µ!",
            "description": "–ü—Ä–∏ –ø–æ–ø—ã—Ç–∫–µ –æ–±–Ω–æ–≤–∏—Ç—å —Å–µ—Ä–≤–µ—Ä–∞ —Å—Ç–æ–ª–∫–Ω—É–ª–∏—Å—å —Å –æ—à–∏–±–∫–æ–π.",
            "color": 12345610
          }]
        }' \
        $DISCORD_PUBLISH_NOTIFY
    - name: SS220 PN2D - Success Release Update
      if: ${{GITHUB.REF_NAME == 'release' && github.repository == 'SerbiaStrong-220/space-station-14' && success()}}
      env:
        DISCORD_PUBLISH_NOTIFY_RELEASE: ${{ secrets.DISCORD_PUBLISH_NOTIFY_RELEASE }}
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{
          "username": "SS220 Changelogger",
          "avatar_url": "https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/refs/heads/master/logo.png",
          "embeds": [{
            "title": "–û–±–Ω–æ–≤–ª–µ–Ω–∏–µ –æ—Ç–ø—Ä–∞–≤–ª–µ–Ω–æ –Ω–∞ —Å–µ—Ä–≤–µ—Ä–∞ üöÄ",
            "description": "–°–µ—Ä–≤–µ—Ä–∞ –∞–≤—Ç–æ–º–∞—Ç–∏—á–µ—Å–∫–∏ –ø–µ—Ä–µ–∑–∞–ø—É—Å—Ç—è—Ç—Å—è –¥–ª—è –æ–±–Ω–æ–≤–ª–µ–Ω–∏—è –≤ –∫–æ–Ω—Ü–µ —Ç–µ–∫—É—â–∏—Ö —Ä–∞—É–Ω–¥–æ–≤!",
            "color": 3447003
          }]
        }' \
        $DISCORD_PUBLISH_NOTIFY_RELEASE
# SS220 Discord Notifier end

# SS220 temp disable discord publish
    # - name: Publish changelog (Discord)
    #   continue-on-error: true
    #   run: Tools/actions_changelogs_since_last_run.py
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     DISCORD_WEBHOOK_URL: ${{ secrets.CHANGELOG_DISCORD_WEBHOOK }}

    # - name: Publish changelog (RSS)
    #   continue-on-error: true
    #   run: Tools/actions_changelog_rss.py
    #   env:
    #     CHANGELOG_RSS_KEY: ${{ secrets.CHANGELOG_RSS_KEY }}
